create table accounts (account_id serial not null, document_number varchar(20) not null, primary key (account_id));
create table operations_types (operation_type_id int4 not null, description varchar(255), primary key (operation_type_id));
create table transactions (transaction_id serial not null, amount numeric(19, 2) not null, event_date timestamp not null, account_id int8 not null, operation_type_id int4 not null, primary key (transaction_id));
alter table accounts add constraint UK_j6o4j12ds9epbx9hl5t7ejokc unique (document_number);
alter table transactions add constraint FK20w7wsg13u9srbq3bd7chfxdh foreign key (account_id) references accounts;
alter table transactions add constraint FK5myt5nhwr3y6shiscij7p5iru foreign key (operation_type_id) references operations_types;
insert into operations_types values(1, 'COMPRA A VISTA');
insert into operations_types values(2, 'COMPRA PARCELADA');
insert into operations_types values(3, 'SAQUE');
insert into operations_types values(4, 'PAGAMENTO');
