version: '3.5'

services:
  postgres-compose:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pismo_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pismodb
      PGDATA: /data/postgres
      DB_HOST: postgres-compose
    volumes:
       - postgres:/var/lib/postgresql/data
       - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
       
    ports:
      - "15432:5432" 
    networks:
      - pismo-api  

    
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    environment:  
      REDIS_HOST: localhost
      
    volumes: 
      - redis:/data


volumes:
    postgres:
      driver: local
    redis:
      driver: local
networks:
  pismo-api:
    driver: bridge      
      
   
  